apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend-app
          image: ghcr.io/marcuslinhares/curriculum-api:latest
          ports:
            - containerPort: 8080
